version: '3'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    ports:
      - "5432:5432"

  keycloak:
#    image: docker.io/bitnami/keycloak:22
    build:
      dockerfile: bitnami/Dockerfile
      context: ..
    depends_on:
      - postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - JAVA_OPTS='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005'
      - KEYCLOAK_ROOT_LOG_LEVEL=DEBUG
      - KEYCLOAK_LOG_LEVEL=debug
    expose:
      - 5005
    ports:
      - "5005:5005"
      - "18080:8080"

volumes:
  postgresql_data:
    driver: local


